### PR TITLE
fix: null handling in vlSelectionTest

### LINKED ISSUE #3782: vlSelectionTest doesn't handle null values
I'm working with Vega-Lite's selections framework, but since `vlSelectionTest` lives in this repo I'm opening the issue here.

Vega-Lite spec for simple pie chart with a null-valued wedge and click highlighting enabled.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple pie chart with embedded data.",
  "data": {
    "values": [
      {"category": 1, "value": 4},
      {"category": 2, "value": 6},
      {"category": 3, "value": 10},
      {"category": 4, "value": 3},
      {"category": 5, "value": 7},
      {"category": 6, "value": 8},
      {"category": null, "value": 10}
    ]
  },
  "mark": "arc",
  "encoding": {
    "theta": {"field": "value", "type": "quantitative"},
    "color": {"field": "category", "type": "nominal"},
    "opacity": {"condition": {"test": {"param": "click"}, "value": 1.0}, "value": 0.5}
  },
  "params": [{
    "name": "click",
    "select": {
      "type": "point",
      "encodings": ["color"]
    }
  }]
}
```

visualization (1)

This compiles into the following Vega spec
```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A simple pie chart with embedded data.",
  "background": "white",
  "padding": 5,
  "width": 200,
  "height": 200,
  "style": "view",
  "data": [
    {"name": "click_store"},
    {
      "name": "source_0",
      "values": [
        {"category": 1, "value": 4},
        {"category": 2, "value": 6},
        {"category": 3, "value": 10},
        {"category": 4, "value": 3},
        {"category": 5, "value": 7},
        {"category": 6, "value": 8},
        {"category": null, "value": 10}
      ]
    },
    {
      "name": "data_0",
      "source": "source_0",
      "transform": [
        {
          "type": "stack",
          "groupby": [],
          "field": "value",
          "sort": {"field": ["category"], "order": ["ascending"]},
          "as": ["value_start", "value_end"],
          "offset": "zero"
        },
        {
          "type": "filter",
          "expr": "isValid(datum[\"value\"]) && isFinite(+datum[\"value\"])"
        }
      ]
    }
  ],
  "signals": [
    {
      "name": "unit",
      "value": {},
      "on": [
        {"events": "mousemove", "update": "isTuple(group()) ? group() : unit"}
      ]
    },
    {
      "name": "click",
      "update": "vlSelectionResolve(\"click_store\", \"union\", true, true)"
    },
    {
      "name": "click_tuple",
      "on": [
        {
          "events": [{"source": "scope", "type": "click"}],
          "update": "datum && item().mark.marktype !== 'group' && indexof(item().mark.role, 'legend') < 0 ? {unit: \"\", fields: click_tuple_fields, values: [(item().isVoronoi ? datum.datum : datum)[\"category\"]]} : null",
          "force": true
        },
        {"events": [{"source": "view", "type": "dblclick"}], "update": "null"}
      ]
    },
    {
      "name": "click_tuple_fields",
      "value": [{"field": "category", "channel": "color", "type": "E"}]
    },
    {
      "name": "click_toggle",
      "value": false,
      "on": [
        {
          "events": [{"source": "scope", "type": "click"}],
          "update": "event.shiftKey"
        },
        {"events": [{"source": "view", "type": "dblclick"}], "update": "false"}
      ]
    },
    {
      "name": "click_modify",
      "on": [
        {
          "events": {"signal": "click_tuple"},
          "update": "modify(\"click_store\", click_toggle ? null : click_tuple, click_toggle ? null : true, click_toggle ? click_tuple : null)"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "marks",
      "type": "arc",
      "style": ["arc"],
      "interactive": true,
      "from": {"data": "data_0"},
      "encode": {
        "update": {
          "fill": {"scale": "color", "field": "category"},
          "opacity": [
            {
              "test": "!length(data(\"click_store\")) || vlSelectionTest(\"click_store\", datum)",
              "value": 1
            },
            {"value": 0.5}
          ],
          "description": {
            "signal": "\"value: \" + (format(datum[\"value\"], \"\")) + \"; category: \" + (isValid(datum[\"category\"]) ? datum[\"category\"] : \"\"+datum[\"category\"])"
          },
          "x": {"signal": "width", "mult": 0.5},
          "y": {"signal": "height", "mult": 0.5},
          "outerRadius": {"signal": "min(width,height)/2"},
          "innerRadius": {"value": 0},
          "startAngle": {"scale": "theta", "field": "value_end"},
          "endAngle": {"scale": "theta", "field": "value_start"}
        }
      }
    }
  ],
  "scales": [
    {
      "name": "theta",
      "type": "linear",
      "domain": {"data": "data_0", "fields": ["value_start", "value_end"]},
      "range": [0, 6.283185307179586],
      "zero": true
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "data_0", "field": "category", "sort": true},
      "range": "category"
    }
  ],
  "legends": [
    {
      "fill": "color",
      "symbolType": "circle",
      "title": "category",
      "encode": {"symbols": {"update": {"opacity": {"value": 1}}}}
    }
  ]
}
```
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIZw1LsJOsyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgUAHkbOoAnmgAjEqR0XBoACwAvgqJyWSpGagATDlRMWgAbCVlmCnpaADMdXlZAAwtIEltFR2oBT0NqJ2Dw+1VYpP5qADss+WVTUtoABzrI5uosgyCgtuomQMAuiUgyOoA1mgg9lDBcLJQbMo0smRooHocECAJAADMbIJlM9cg0lJg0jhliAAI4MJCyHSBHSkEC3L6CVKgiFwKHPOajDLwxHI2RsBC-KJ4pRsHBIKB0KqJOQ-HRyUFtCCYUFs9RIBDk4RQJ63WHLTKy+rLPqUMRFW6i8UQeKgWTi5FQKVPJQQUlwKDC8IgBFI544Ni-YVKD5fH5-bWoOJDNiE9QgG5FG5AA)

When clicking on the 1-valued wedge, the `click_store` dataset is set to this

Screenshot 2023-07-21 at 11 11 16 AM
and all of the other wedges turn transparent:

visualization (2)

When clicking on the null-valued wdget, the `click_store` dataset is set to this

Screenshot 2023-07-21 at 11 12 44 AM

but the wedge is not highlighted and this error is raised in the console:

```
index-1cb9cf04.js:685 TypeError: Cannot read properties of null (reading '0')
    at Zte (index-1cb9cf04.js:84:10747)
    at Object.KUe [as vlSelectionTest] (index-1cb9cf04.js:84:11344)
    at Object.eval (eval at j_ (index-1cb9cf04.js:84:24669), <anonymous>:3:143)
    at index-1cb9cf04.js:82:23367
    at Array.forEach (<anonymous>)
    at eg (index-1cb9cf04.js:76:33193)
    at Rg.visit (index-1cb9cf04.js:81:11952)
    at zge.transform (index-1cb9cf04.js:82:23354)
    at zge.evaluate (index-1cb9cf04.js:81:16773)
    at zge.run (index-1cb9cf04.js:81:16630)
```

I'm doing this in the Vega editor, and it looks like the Vega bundle is minified. But the error is happening somewhere in `vlSelectionTest`.

### PR DESCRIPTION
**Pull request by jonmmease**
Closes #3782

The issue was this check: `isDate(values[i][0])`. When `values` is `[1]`, `values[0]` is `1` and `(1)[0]` is `undefined` (but not an error). But when `values` is `[null]`, `values[0]` is `null` and `(null)[0]` is an error.

I may have missed it, but I didn't see any low-level unit tests for `vlSelectionTest`. I added the example from the issue as `packages/vega/test/specs-valid/nulls-selection.vg.json` so that it was easy to confirm the fix manually, but let me know if I should remove this.

Thanks!

### CODE REVIEW

**Comment by jonmmease** [comment]
Test is failing with this error:

```
ERROR Error: ENOENT: no such file or directory, open '/home/runner/work/vega/vega/packages/vega/test/scenegraphs/nulls-selection.json'
```

I jus added nulls-selection.json to `packages/vega/test/specs-valid/nulls-selection.vg.json`. Let me know if I should remove it, or if there's something I should do so that it ends up in `/home/runner/work/vega/vega/packages/vega/test/scenegraphs/nulls-selection.json` where the test is looking for it.

**Comment by jonmmease** [comment]
I got the tests passing and this is ready for a look @arvind

**Comment by jonmmease** [comment]
Friendly ping @arvind @domoritz @jheer

File: packages/vega-selections/src/selectionTest.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ function testPoint(datum, entry) {
 
     if (isDate(dval)) dval = toNumber(dval);
     if (isDate(values[i])) values[i] = toNumber(values[i]);
-    if (isDate(values[i][0])) values[i] = values[i].map(toNumber);
+    if (values[i] && isDate(values[i][0])) values[i] = values[i].map(toNumber);
```
Comment (arvind) [inline packages/vega-selections/src/selectionTest.js:25]: Thanks for catching this @jonmmease and apologies for the delay. I think it would be more accurate to switch to this because the rest of the statement (particularly `values[i].map`) assumes that `values[i]` is an Array. 

```suggestion
    if (isArray(values[i]) && isDate(values[i][0])) values[i] = values[i].map(toNumber);
```

(`isArray` is already imported from `vega-util` so this should be ok.)

**Review by arvind — CHANGES_REQUESTED** [review]

File: packages/vega-selections/src/selectionTest.js (hunk 1 above)
Comment (jonmmease) [reply packages/vega-selections/src/selectionTest.js:25]: Sounds good!

**Comment by jonmmease** [comment]
should be ready to go!

**Comment by arvind** [comment]
Thanks @jonmmease! 🙏
